version: "2"
services:
  app:
    container_name: surveys
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:8000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
