apiVersion: "v1"
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    app: surveys
spec:
  ports:
  - port: 27017
    name: mongo
    targetPort: 27017
  selector:
    name: mongo
    app: surveys
