apiVersion: "v1"
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
    app: surveys
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
          protocol: TCP
