apiVersion: "v1"
kind: Pod
metadata:
  name: surveys
  labels:
    name: surveys
    app: surveys
spec:
  containers:
    - name: web
      image: craigargh/surveys
      ports:
        - containerPort: 8000
          name: http
          protocol: TCP
