apiVersion: v1
kind: Service
metadata:
  name: surveys-service
  labels:
    name: surveys-service
    app: surveys
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 8000
     protocol: TCP
  selector:
    name: surveys
    app: surveys